### ISSUE TITLE
RandomPatches crashing with Connectivity and Create mod

### ISSUE THREAD

**Issue by sirben99** [TheRandomLabs/RandomPatches#231]
Hey!

It seems that when RandomPatches, Connectivity and Create are put together, Create doesent load. Removing any one of them works, meaning they work indivicually, but not together. Connectivity creator sayd that the issue is on RandomPatches (https://github.com/someaddons/connectivity/issues/2) so i desided to open the issue here.

Forge: 36.1.24
Minecraft: 1.16.5
Connectivity: 1.6-1.16.5
Create: 1.16.4+ v0.3.1c
RandomPatches: 2.4.4-forge

Crash.txt:
[crash-2021-06-03_19.28.15-fml.txt](https://github.com/TheRandomLabs/RandomPatches/files/6597345/crash-2021-06-03_19.28.15-fml.txt)

Latest.log:
[latest.log](https://github.com/TheRandomLabs/RandomPatches/files/6597352/latest.log)

Ben

**Comment by BugmanBugman** [comment]
Can confirm this

**Comment by sirben99** [comment]
I should add that Connectivity instructed how to fix this problem, but random patches still should fix it them self if possible:

"Set this in the randompatches.toml config file so random patches does not crash when started alongside connectivity mixin_blacklist = ["ServerPlayNetHandlerKeepAlive"]
Connectivity has some overlap with randompatches and happens to apply first, which makes random patches crash."
Source: https://www.curseforge.com/minecraft/mc-mods/connectivity in "Randompatches (in)compatibility" section of the description.

**Comment by Skulaurun** [comment]
Can confirm the conflicts (with Create and other mods), after removing Random patches from mods folder, everything works fine.


![image](https://user-images.githubusercontent.com/31413184/179581801-b967392b-a55b-4066-91db-aa4df4afce44.png)

**Comment by FriendlyFriend67** [comment]
i dont have randompatches in my mod folder and its still crashing

**Comment by FriendlyFriend67** [comment]
its 1.16.5 forge,
